server:
  port: 7080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/global?currentSchema=know&autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid

#自定义配置文件
#上传视频本地保存地址
videoSavePath: /Users/soanr/Desktop/videos
