server:
  port: 7080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/global?currentSchema=know&autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid

#自定义配置文件
#上传视频本地保存地址
videoSavePath: /Users/soanr/Desktop/videos

wx:
  mp:
    appId: wxe05bcbd16155d028
    secret: c6304e23275b2d8ef4058f6f465d5f7c
    token: erwerwerew3243242